parameters:
    # transport
    eltrino_amazon.amazon_rest_transport.class:                              Eltrino\OroCrmAmazonBundle\Provider\Transport\AmazonRestTransport

    # providers
    eltrino_amazon.provider.amazon_channel_type.class:                       Eltrino\OroCrmAmazonBundle\Provider\AmazonChannelType

    # forms
    eltrino_amazon.form.type.amazon_rest_transport_setting.class:            Eltrino\OroCrmAmazonBundle\Form\Type\AmazonRestTransportSettingFormType

    eltrino_amazon.order.factory.class:                                      Eltrino\OroCrmAmazonBundle\Model\Order\OrderFactory

    eltrino_amazon.filters.factory_class:                                    Eltrino\OroCrmAmazonBundle\Amazon\Filters\FiltersFactory

    eltrino_amazon.navigation.listener_class:                                Eltrino\OroCrmAmazonBundle\EventListener\AmazonNavigationListener

    eltrino_amazon.client.rest_client_factory.class:                         Eltrino\OroCrmAmazonBundle\Amazon\Client\RestClientFactory

services:
   # transport
    eltrino_amazon.amazon_rest_transport:
        class: %eltrino_amazon.amazon_rest_transport.class%
        arguments:
            - @eltrino_amazon.client_rest_client_factory
            - @eltrino_amazon.filters.factory
        tags:
            - { name: oro_integration.transport, type: amazon_rest, channel_type: amazon}

    eltrino_amazon.client_rest_client_factory:
        class: %eltrino_amazon.client.rest_client_factory.class%

   # providers
    eltrino_amazon.provider.amazon_channel_type:
        class: %eltrino_amazon.provider.amazon_channel_type.class%
        tags:
            - { name: oro_integration.channel, type: amazon }

    # forms
    eltrino_amazon.form.type.amazon_rest_transport_setting:
        class: %eltrino_amazon.form.type.amazon_rest_transport_setting.class%
        tags:
            - { name: form.type, alias: eltrino_amazon_rest_transport_setting_form_type }

    eltrino_amazon.order.factory:
        class: %eltrino_amazon.order.factory.class%
        arguments:
            - @doctrine.orm.entity_manager

    eltrino_amazon.filters.factory:
        class: %eltrino_amazon.filters.factory_class%

    # event listeners
    eltrino_amazon.event_listener.navigation:
        class: %eltrino_amazon.navigation.listener_class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure, priority: -10 }

    eltrino_amazon.event_listener.order_items_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
            - 'id'
            - false
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.amazon-orderitem-grid, method: onBuildAfter }
