language: php

php:
  - 7.0
  - 7.1
  - hhvm

sudo: false

branches:
  only:
    - master

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - if [[ "$TRAVIS_PHP_VERSION"  = "hhvm" ]]; then cat travis.php.ini >> /etc/hhvm/php.ini ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-add travis.php.ini ; fi
  - composer global require fxp/composer-asset-plugin:~1.3@dev
  - composer self-update

install:
  - composer install --prefer-source --profile

script: if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/phpunit --coverage-clover=coverage.clover; else php vendor/bin/phpunit; fi

after_script:
  - if [ -e coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ -e coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
