datagrids:
    amazon-orders-grid:
        source:
            type: orm
            query:
                select:
                    - o
                    - ch.name as channelName
                from:
                    - { table: %eltrino_amazon.order.entity.class%, alias: o }
                join:
                    left:
                        - { join: o.channel, alias: ch }
        columns:
            channelName:
                label: eltrino.orocrmamazon.order.channel.label
            amazonOrderId:
                label: eltrino.orocrmamazon.order.amazon_order_id.label
            marketPlaceId:
                label: eltrino.orocrmamazon.order.market_place_id.label
            salesChannel:
                label: eltrino.orocrmamazon.order.sales_channel.label
            orderType:
                label: eltrino.orocrmamazon.order.order_type.label
            orderStatus:
                label: eltrino.orocrmamazon.order.order_status.label
            fulfillmentChannel:
                label: eltrino.orocrmamazon.order.fulfillment_channel.label
            shipServiceLevel:
                label: eltrino.orocrmamazon.order.ship_service_level.label
            shipmentServiceLevelCategory:
                label: eltrino.orocrmamazon.order.shipment_service_level_category.label
            numberOfItemsShipped:
                label: eltrino.orocrmamazon.order.number_of_items_shipped.label
            numberOfItemsUnshipped:
                label: eltrino.orocrmamazon.order.number_of_items_unshipped.label
            currencyId:
                label: eltrino.orocrmamazon.order.currency_id.label
            paymentMethod:
                label: eltrino.orocrmamazon.order.payment_method.label
            totalAmount:
                label: eltrino.orocrmamazon.order.total_amount.label
                type:   localized_number
                method: formatCurrency
                context_resolver: Eltrino\OroCrmAmazonBundle\Grid\FormatterContextResolver::getResolverCurrencyClosure
            createdAt:
                label: eltrino.orocrmamazon.order.created_at.label
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type: url
                route: eltrino_amazon_order_view
                params: [ id ]
        sorters:
            columns:
                amazonOrderId:                      { data_name: o.amazonOrderId }
                marketPlaceId:                      { data_name: o.marketPlaceId }
                salesChannel:                       { data_name: o.salesChannel }
                orderType:                          { data_name: o.orderType }
                orderStatus:                        { data_name: o.orderStatus }
                channelName:                        { data_name: ch.name }
                fulfillmentChannel:                 { data_name: o.fulfillmentChannel }
                shipServiceLevel:                   { data_name: o.shipServiceLevel }
                shipmentServiceLevelCategory:       { data_name: o.shipmentServiceLevelCategory }
                numberOfItemsShipped:               { data_name: o.numberOfItemsShipped }
                numberOfItemsUnshipped:             { data_name: o.numberOfItemsUnshipped }
                currencyId:                         { data_name: o.currencyId }
                paymentMethod:                      { data_name: o.paymentMethod }
                totalAmount:                        { data_name: o.totalAmount }
                createdAt:                          { data_name: o.createdAt }
        filters:
            columns:
                channelName:
                    type: entity
                    data_name: ch.id
                    options:
                        field_options:
                            multiple: true
                            class: OroIntegrationBundle:Channel
                            property: name
                amazonOrderId:
                    type: string
                    data_name: o.amazonOrderId
                marketPlaceId:
                    type: string
                    data_name: o.marketPlaceId
                salesChannel:
                    type: string
                    data_name: o.salesChannel
                orderType:
                    type: string
                    data_name: o.orderType
                orderStatus:
                    type: string
                    data_name: o.orderStatus
                fulfillmentChannel:
                    type: string
                    data_name: o.fulfillmentChannel
                shipServiceLevel:
                   type: string
                   data_name: o.shipServiceLevel
                shipmentServiceLevelCategory:
                   type: string
                   data_name: o.shipmentServiceLevelCategory
                numberOfItemsShipped:
                    type:             number
                    data_name:        o.numberOfItemsShipped
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                numberOfItemsUnshipped:
                    type:             number
                    data_name:        o.numberOfItemsUnshipped
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                paymentMethod:
                    type: string
                    data_name: o.paymentMethod
                totalAmount:
                    type:             number
                    data_name:        o.totalAmount
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
        actions:
            view:
                type:         navigate
                label:        eltrino.orocrmamazon.datagrid.actions.view.label
                link:         view_link
                icon:         eye-open
                rowAction:    true
        options:
            entityHint: order

    amazon-orderitem-grid:
        source:
            type: orm
            query:
                select:
                    - o
                from:
                    - { table: %eltrino_amazon.order_item.entity.class%, alias: o }
                where:
                    and:
                        - o.order = :id
        columns:
            asin:
                label: eltrino.orocrmamazon.orderitem.asin.label
            orderItemId:
                label: eltrino.orocrmamazon.orderitem.order_item_id.label
            sellerSku:
                label: eltrino.orocrmamazon.orderitem.seller_sku.label
            title:
                label: eltrino.orocrmamazon.orderitem.title.label
            quantityOrdered:
                label: eltrino.orocrmamazon.orderitem.quantity_ordered.label
            quantityShipped:
                label: eltrino.orocrmamazon.orderitem.quantity_shipped.label
            condition:
                label: eltrino.orocrmamazon.orderitem.condition.label
            shippingPriceAmount:
                label:  eltrino.orocrmamazon.orderitem.shipping_price_amount.label
                type:   localized_number
                method: formatCurrency
                context_resolver: Eltrino\OroCrmAmazonBundle\Grid\FormatterContextResolver::getResolverShippingCurrencyClosure
            giftWrapPriceAmount:
                label:  eltrino.orocrmamazon.orderitem.gift_wrap_price_amount.label
                type:   localized_number
                method: formatCurrency
                context_resolver: Eltrino\OroCrmAmazonBundle\Grid\FormatterContextResolver::getResolverGiftCurrencyClosure
            itemPriceAmount:
                label:  eltrino.orocrmamazon.orderitem.item_price_amount.label
                type:   localized_number
                method: formatCurrency
                context_resolver: Eltrino\OroCrmAmazonBundle\Grid\FormatterContextResolver::getResolverItemCurrencyClosure
        sorters:
            columns:
                asin:                  { data_name: o.asin }
                orderItemId:           { data_name: o.orderItemId }
                sellerSku:             { data_name: o.sellerSku }
                title:                 { data_name: o.title }
                quantityOrdered:       { data_name: o.quantityOrdered }
                quantityShipped:       { data_name: o.quantityShipped }
                condition:             { data_name: o.condition }
                shippingPriceAmount:   { data_name: o.shippingPriceAmount }
                giftWrapPriceAmount:   { data_name: o.giftWrapPriceAmount }
                itemPriceAmount:       { data_name: o.itemPriceAmount }
        filters:
            columns:
                asin:
                    type: string
                    data_name: o.asin
                orderItemId:
                    type: string
                    data_name: o.orderItemId
                sellerSku:
                    type: string
                    data_name: o.sellerSku
                title:
                    type: string
                    data_name: o.title
                quantityOrdered:
                    type:             number
                    data_name:        o.quantityOrdered
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                quantityShipped:
                    type:             number
                    data_name:        o.quantityShipped
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                condition:
                    type: string
                    data_name: o.condition
                shippingPriceAmount:
                    type:             number
                    data_name:        o.shippingPriceAmount
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                giftWrapPriceAmount:
                    type:             number
                    data_name:        o.giftWrapPriceAmount
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                itemPriceAmount:
                    type:             number
                    data_name:        o.itemPriceAmount
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
        options:
            entityHint: order item