navigation:
    menu_config:
        items:
            eltrino_amazon_orders:
                label: 'eltrino.orocrmamazon.navigation.items.eltrino_amazon_orders.label'
                route: 'eltrino_amazon_order_index'
                extras:
                    routes: ['eltrino_amazon_*']
                    position: 20

            eltrino_sales:
                label: 'eltrino.orocrmamazon.navigation.items.eltrino_sales.label'
                uri: "#"

        tree:
            application_menu:
                children:
                    eltrino_sales:
                        children:
                            eltrino_amazon_orders: ~

    titles:
        eltrino_amazon_order_index: 'eltrino.orocrmamazon.navigation.titles.eltrino_amazon_order_index.label'
        eltrino_amazon_order_view:  'eltrino.orocrmamazon.navigation.titles.eltrino_amazon_order_view.label'
